// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6N0QOiBtJDMxx2CHnKjFBXrOVz6QWJ48',
    appId: '1:78894173771:web:dd6e7b3410042cb5d047ce',
    messagingSenderId: '78894173771',
    projectId: 'authentication-ce0e6',
    authDomain: 'authentication-ce0e6.firebaseapp.com',
    storageBucket: 'authentication-ce0e6.firebasestorage.app',
    measurementId: 'G-24JMLX99NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzTTypW4xtJxI38JyCrsIoKzq4v-SnCZw',
    appId: '1:78894173771:android:98ba37a4ce39b5dbd047ce',
    messagingSenderId: '78894173771',
    projectId: 'authentication-ce0e6',
    storageBucket: 'authentication-ce0e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0HDKLvO4SGviAr3BtilahIVVcaJ1qt6I',
    appId: '1:78894173771:ios:533a17eb2a6acf1bd047ce',
    messagingSenderId: '78894173771',
    projectId: 'authentication-ce0e6',
    storageBucket: 'authentication-ce0e6.firebasestorage.app',
    iosBundleId: 'com.example.authUiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0HDKLvO4SGviAr3BtilahIVVcaJ1qt6I',
    appId: '1:78894173771:ios:533a17eb2a6acf1bd047ce',
    messagingSenderId: '78894173771',
    projectId: 'authentication-ce0e6',
    storageBucket: 'authentication-ce0e6.firebasestorage.app',
    iosBundleId: 'com.example.authUiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6N0QOiBtJDMxx2CHnKjFBXrOVz6QWJ48',
    appId: '1:78894173771:web:115bc6a8e1baf73ed047ce',
    messagingSenderId: '78894173771',
    projectId: 'authentication-ce0e6',
    authDomain: 'authentication-ce0e6.firebaseapp.com',
    storageBucket: 'authentication-ce0e6.firebasestorage.app',
    measurementId: 'G-MRYD5ZCJRG',
  );
}
